[package]
name = "rip-runtime-state"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rip-actuator-model = { path = "../../plant/actuator-model" }
rip-hybrid-control = { path = "../../control/hybrid-control" }
rip-robot-domain = { path = "../../plant/robot-domain" }

[lib]
path = "src/lib.rs"
