[package]
name = "rip-firmware-stm32f103"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
rip-estimator-input-adapter = { path = "../../adapters/estimator-input" }
rip-measurement-model = { path = "../../../plant/measurement-model" }
rip-plant-observation = { path = "../../../plant/plant-observation" }
rip-robot-domain = { path = "../../../plant/robot-domain" }
rip-state-estimator = { path = "../../../supervisor/state-estimator" }
stm32f1xx-hal = { version = "0.11.0", features = ["stm32f103", "medium"] }
